const express=require("express"),crypto=require("crypto"),Database=require("better-sqlite3"),path=require("path");
const app=express(),PORT=process.env.PORT||8080,BOT_TOKEN=process.env.BOT_TOKEN||"",BOT_USERNAME=process.env.BOT_USERNAME||"my_crypto_miner_game_bot",ADS_BLOCK_ID=process.env.ADS_BLOCK_ID||"52244";
app.use(express.json({limit:"100kb"}));app.use((q,r,n)=>{r.header("Access-Control-Allow-Origin","*");r.header("Access-Control-Allow-Methods","GET,POST,OPTIONS");r.header("Access-Control-Allow-Headers","Content-Type, X-Telegram-Init-Data");if(q.method==="OPTIONS")return r.sendStatus(204);n()});
const db=new Database(path.join(__dirname,"falcon.db"));db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT DEFAULT '',balance INTEGER DEFAULT 0,energy INTEGER DEFAULT 1500,max_energy INTEGER DEFAULT 1500,power INTEGER DEFAULT 1,passive_per_minute INTEGER DEFAULT 0,regen INTEGER DEFAULT 12,level INTEGER DEFAULT 1,xp INTEGER DEFAULT 0,last_mine INTEGER DEFAULT 0,last_energy_update INTEGER DEFAULT 0,last_daily INTEGER DEFAULT 0,streak INTEGER DEFAULT 0,total_mined INTEGER DEFAULT 0,ad_views INTEGER DEFAULT 0,completed_contracts INTEGER DEFAULT 0,referral_count INTEGER DEFAULT 0,referred_by INTEGER,created_at INTEGER DEFAULT 0,updated_at INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS withdrawals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,amount INTEGER,wallet TEXT,status TEXT DEFAULT 'pending',created_at INTEGER);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,amount INTEGER,label TEXT,created_at INTEGER);
CREATE TABLE IF NOT EXISTS contracts(user_id INTEGER,contract_id TEXT,progress INTEGER DEFAULT 0,claimed INTEGER DEFAULT 0,PRIMARY KEY(user_id,contract_id));`);
function col(n,t,d){if(!db.prepare("PRAGMA table_info(users)").all().some(x=>x.name===n))db.exec(`ALTER TABLE users ADD COLUMN ${n} ${t} DEFAULT ${d}`)}
["username","max_energy","passive_per_minute","regen","level","xp","last_mine","last_energy_update","last_daily","streak","total_mined","ad_views","completed_contracts","referral_count","referred_by","created_at","updated_at"].forEach((x)=>{const defs={username:["TEXT","''"],max_energy:["INTEGER","1500"],passive_per_minute:["INTEGER","0"],regen:["INTEGER","12"],level:["INTEGER","1"],xp:["INTEGER","0"],last_mine:["INTEGER","0"],last_energy_update:["INTEGER","0"],last_daily:["INTEGER","0"],streak:["INTEGER","0"],total_mined:["INTEGER","0"],ad_views:["INTEGER","0"],completed_contracts:["INTEGER","0"],referral_count:["INTEGER","0"],referred_by:["INTEGER","NULL"],created_at:["INTEGER","0"],updated_at:["INTEGER","0"]};col(x,...defs[x])});
const now=()=>Math.floor(Date.now()/1000),xpNext=l=>100+(l-1)*75;
function auth(req){const s=req.header("X-Telegram-Init-Data");if(!s||!BOT_TOKEN)throw Error("Telegram авторизация не настроена.");const p=new URLSearchParams(s),h=p.get("hash");let a=[];for(const [k,v]of p)if(k!=="hash")a.push(k+"="+v);a.sort();const sec=crypto.createHmac("sha256","WebAppData").update(BOT_TOKEN).digest(),calc=crypto.createHmac("sha256",sec).update(a.join("\n")).digest("hex");if(!h||calc!==h)throw Error("Недействительная Telegram-сессия.");if(now()-Number(p.get("auth_date")||0)>86400)throw Error("Telegram-сессия устарела.");const u=JSON.parse(p.get("user")||"{}");if(!u.id)throw Error("Не найден Telegram user ID.");return u}
function user(t){let u=db.prepare("SELECT * FROM users WHERE id=?").get(t.id);if(!u){db.prepare("INSERT INTO users(id,username,created_at,updated_at,last_energy_update)VALUES(?,?,?,?,?)").run(t.id,t.username||t.first_name||"",now(),now(),now());u=db.prepare("SELECT * FROM users WHERE id=?").get(t.id)}return u}
function energy(u){let d=Math.max(0,now()-u.last_energy_update),e=Math.min(u.max_energy,u.energy+d*u.regen);if(d)db.prepare("UPDATE users SET energy=?,last_energy_update=? WHERE id=?").run(e,now(),u.id);u.energy=e;return u}
function tx(id,a,l){db.prepare("INSERT INTO transactions(user_id,amount,label,created_at)VALUES(?,?,?,?)").run(id,a,l,now())}
function xp(id,n){let u=db.prepare("SELECT level,xp FROM users WHERE id=?").get(id),x=u.xp+n,l=u.level;while(x>=xpNext(l)){x-=xpNext(l);l++}db.prepare("UPDATE users SET xp=?,level=? WHERE id=?").run(x,l,id)}
function contracts(u){const d=[["mine100","Первая сотня","Сделай 100 добывающих действий.",100,100],["mine1000","Разведка сектора","Добыть 1 000 TONF.",1000,500],["upgrade2","Инженерный старт","Купить 2 улучшения.",2,700],["daily3","Три дня связи","Получить 3 ежедневных бонуса.",3,900]];return d.map(x=>{const r=db.prepare("SELECT * FROM contracts WHERE user_id=? AND contract_id=?").get(u.id,x[0]);let p=0;if(x[0]==="mine100"||x[0]==="mine1000")p=Math.min(x[3],u.total_mined);if(x[0]==="upgrade2")p=Math.min(2,Math.max(0,u.power-1));if(x[0]==="daily3")p=Math.min(3,Math.max(0,u.streak));return{id:x[0],title:x[1],description:x[2],target:x[3],reward:x[4],progress:p,completed:!!r?.claimed,claimable:p>=x[3]&&!r?.claimed}})}
function state(u){u=energy(u);u=db.prepare("SELECT * FROM users WHERE id=?").get(u.id);return{balance:u.balance,energy:u.energy,maxEnergy:u.max_energy,power:u.power,passivePerMinute:u.passive_per_minute,level:u.level,xp:u.xp,nextXp:xpNext(u.level),streak:u.streak,referrals:u.referral_count,dailyAvailable:now()-u.last_daily>=86400,referralLink:`https://t.me/${BOT_USERNAME}?start=ref_${u.id}`,adsBlockId:ADS_BLOCK_ID,upgrades:{power:{cost:Math.floor(100*Math.pow(1.65,Math.max(0,u.power-1)))},energy:{cost:Math.floor(250*Math.pow(1.7,Math.max(0,(u.max_energy-1500)/250)))},regen:{cost:Math.floor(400*Math.pow(1.75,Math.max(0,(u.regen-12)/4)))}},history:db.prepare("SELECT amount,label FROM transactions WHERE user_id=? ORDER BY id DESC LIMIT 20").all(u.id),contracts:contracts(u),stats:{totalMined:u.total_mined,adViews:u.ad_views,completedContracts:u.completed_contracts}}}
app.get("/health",(q,r)=>r.json({ok:true,server:"TON Falcon",adsBlockId:ADS_BLOCK_ID}));app.use(express.static(__dirname));app.get("/",(q,r)=>r.sendFile(path.join(__dirname,"index.html")));
app.get("/api/state",(q,r)=>{try{const u=user(auth(q));r.json({state:state(u)})}catch(e){r.status(401).json({error:e.message})}});
app.post("/api/mine",(q,r)=>{try{const t=auth(q),u=energy(user(t)),n=now();if(n-u.last_mine<0.5)throw Error("Слишком быстро. Подожди мгновение.");if(u.energy<u.power)throw Error("Недостаточно энергии.");db.prepare("UPDATE users SET balance=balance+?,energy=energy-?,last_mine=?,total_mined=total_mined+? WHERE id=?").run(u.power,u.power,n,u.power,t.id);tx(t.id,u.power,"Майнинг");xp(t.id,1);r.json({state:state(user(t))})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/upgrade",(q,r)=>{try{const t=auth(q),u=energy(user(t)),type=q.body?.type;let c,sql,label;if(type==="power"){c=Math.floor(100*Math.pow(1.65,Math.max(0,u.power-1)));sql="UPDATE users SET balance=balance-?,power=power+1,passive_per_minute=passive_per_minute+5 WHERE id=?";label="Mining Core"}else if(type==="energy"){c=Math.floor(250*Math.pow(1.7,Math.max(0,(u.max_energy-1500)/250)));sql="UPDATE users SET balance=balance-?,max_energy=max_energy+250,energy=energy+250 WHERE id=?";label="Energy Cell"}else if(type==="regen"){c=Math.floor(400*Math.pow(1.75,Math.max(0,(u.regen-12)/4)));sql="UPDATE users SET balance=balance-?,regen=regen+4 WHERE id=?";label="Cooler"}else throw Error("Неизвестное улучшение.");if(u.balance<c)throw Error("Недостаточно TONF.");db.prepare(sql).run(c,t.id);tx(t.id,-c,"Улучшение "+label);xp(t.id,10);r.json({state:state(user(t))})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/daily",(q,r)=>{try{const t=auth(q),u=user(t),n=now();if(n-u.last_daily<86400)throw Error("Ежедневный бонус уже получен.");const s=u.last_daily&&n-u.last_daily<172800?u.streak+1:1,rew=250+Math.min(s,7)*75;db.prepare("UPDATE users SET balance=balance+?,last_daily=?,streak=? WHERE id=?").run(rew,n,s,t.id);tx(t.id,rew,"Ежедневный бонус");xp(t.id,20);r.json({state:state(user(t))})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/ad-reward",(q,r)=>{try{const t=auth(q),u=user(t),last=db.prepare("SELECT created_at FROM transactions WHERE user_id=? AND label='Reward-реклама' ORDER BY id DESC LIMIT 1").get(t.id);if(last&&now()-last.created_at<60)throw Error("Рекламный бонус можно получать не чаще раза в минуту.");db.prepare("UPDATE users SET balance=balance+50,ad_views=ad_views+1 WHERE id=?").run(t.id);tx(t.id,50,"Reward-реклама");xp(t.id,5);r.json({state:state(user(t))})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/contract/claim",(q,r)=>{try{const t=auth(q),u=user(t),c=contracts(u).find(x=>x.id===String(q.body?.contractId||""));if(!c||!c.claimable)throw Error("Контракт ещё не выполнен.");db.prepare("INSERT OR REPLACE INTO contracts(user_id,contract_id,progress,claimed)VALUES(?,?,?,1)").run(t.id,c.id,c.progress);db.prepare("UPDATE users SET balance=balance+?,completed_contracts=completed_contracts+1 WHERE id=?").run(c.reward,t.id);tx(t.id,c.reward,"Контракт: "+c.title);xp(t.id,25);r.json({state:state(user(t))})}catch(e){r.status(400).json({error:e.message})}});
app.post("/api/withdraw",(q,r)=>{try{const t=auth(q),u=user(t),amount=Number(q.body?.amount||0),wallet=String(q.body?.wallet||"").trim();if(amount<150000||amount>u.balance)throw Error("Недостаточный баланс или сумма меньше 150 000 TONF.");if(!/^(UQ|EQ)[A-Za-z0-9_-]{20,80}$/.test(wallet)&&!/^[A-Za-z0-9_-]+\.ton$/.test(wallet))throw Error("Проверь TON-адрес.");const x=db.prepare("INSERT INTO withdrawals(user_id,amount,wallet,status,created_at)VALUES(?,?,?,?,?)").run(t.id,amount,wallet,"pending",now());db.prepare("UPDATE users SET balance=balance-? WHERE id=?").run(amount,t.id);tx(t.id,-amount,"Заявка на вывод");r.json({withdrawalId:x.lastInsertRowid,state:state(user(t))})}catch(e){r.status(400).json({error:e.message})}});
app.listen(PORT,"0.0.0.0",()=>console.log("TON Falcon listening on "+PORT+"; AdsGram "+ADS_BLOCK_ID));
